### ISSUE TITLE
create new "generate" command.

### ISSUE THREAD

**Issue by craigmonson** [craigmonson/colonize#10]
The "generate" command would add a new directory (leaf or branch), with the config directory initialized with what it knows about the operational environment.  IE:  It will drop down through the already existing configs, and compile info about the different environments, then output appropriate files into the config.

ex:
/foo
/foo/env/dev.tfvars
/foo/env/prod.tfvars

in the 'foo' directory, running "colonize generate web" would create:

/foo/web/env/dev.tfvars
/foo/web/env/prod.tfvars

**Comment by jyore** [comment]
Might want to touch a `make_order` file too, if this is for a branch. Maybe we also be more specific about what is generated, i.e. `colonize generate branch <name> [options]`, `colonize generate leaf <name> [options]`, `colonize generate some-new-feature <name> [options]`.

Some options for the branch, for example, could be a list of leafs to generate under it:
`colonize generate branch myapp --leafs vpc,database,web`

would result in something like:
```
myapp
├── database
│   └── main.tf
├── env
│   ├── dev.tfvars
│   └── prod.tfvars
├── make_order.txt
├── vpc
│   └── main.tf
└── web
    └── main.tf
```

and content of make_order.txt would be set to match the order passed into the list

```
vpc
database
web
```

**Comment by jyore** [comment]
could maybe use `init` or `generate` instead of both as well...

`colonize init <project|branch|leaf|other> [options]`
or
`colonize generate <project|branch|leaf|other> [options]`

**Comment by craigmonson** [comment]
Yea, I like the idea of both init (to initialize a new colonize project) and generate (to build a leaf or branch)
