### ISSUE TITLE
Add in automatic building of remote_state references

### ISSUE THREAD

**Issue by jyore** [craigmonson/colonize#2]
In the previous version, it automatically generated remote state blocks for the VPC, Security Groups and IAM leafs.

After a make plan, for example, the VPC remote state would be generated
```
$ cat _vpc_remote_state.tf
data "terraform_remote_state" "vpc" {
  backend = "s3"
  config {
    bucket = "terraform-states-bucket"
    key    = "vpc_account_nonprod.tfstate"
    region = "us-west-2"
  }
}
```

This made referencing VPC/account level resources, much easier, without having to worry about manually defining these data resources in each leaf. 

A possible idea, would be to use the .colonize.yaml file to specify specific leafs or branches to generate remote_state for...or just generate it for each leaf, regardless.

If going down the .colonize.yaml route, something like:

```
generate_remote_datasources:
  - vpc
  - security_groups
  - iam
```

This could then scan the leafs and determine the bucket location, and generate files for each `_<leaf-name>_remote_state.tf`. Again, this could alternatively just be done for each leaf, by default, potentially. They could also all be merged into a single file, if necessary.

**Comment by craigmonson** [comment]
You should be able to do this by just straight up terraform.  You can build out the bucket and key info using the colonize variable bindings.  The remote state can be added as a terraform file, and that should get setup on the leaf when colonize preps.

**Comment by jyore** [comment]
Yeah, you can do it via normal TF, but was nice having it readily available without having to define in the make version ;)

**Comment by jyore** [comment]
Yep, it is easy enough to add in these datasource blocks as TF templates in the `env` folder. Then they will get pulled into the `_combined.tf` file for reference where needed.

Will go ahead and close this as won't fix
