### ISSUE TITLE
Indicate long running process

### ISSUE THREAD

**Issue by jyore** [craigmonson/colonize#24]
I am launching some RDS instances, which can take some time...a lot of time...

Currently, the output is being captured and printed at the end. The downside to this, is that Terraform is waiting for the creation to end, and Colonize looks like nothing is happening.

I am staring at this for the entire time until the end (took about 10-15m):
```
$ colonize apply
Running remote setup
Remote configuration updated
Remote state configured and pulled.

Executing terraform apply
```

It would be nice to indicate some sort of status that the process is still running OK or use a pipe to pipe the output from TF as it is running, so the output shows up in real-time.

**Comment by craigmonson** [comment]
+1 for a pipe.
