### ISSUE TITLE
Environment required on `clean` command?

### ISSUE THREAD

**Issue by jyore** [craigmonson/colonize#3]
Should this be required?

Just clean may be sufficient:
`$ colonize clean`

Currently, it gives:
```
$ colonize clean 
environment can not be empty
```

You can pass any environment name to get it to execute, however
```
$ colonize clean -e anything
```

**Comment by craigmonson** [comment]
Yea, I think this is a bug.

**Comment by jyore** [comment]
Looked into this briefly. I think it may require some refactoring as the root command currently requires the environment variable, which is why the clean command is also requiring it
