### ISSUE TITLE
Create init command

### ISSUE THREAD

**Issue by craigmonson** [craigmonson/colonize#8]
Like many tools, an initialize command (init) would be super useful for setting up a new project with colonize.  This would create a generic .colonize.yaml in the root of the project, a config ('env') directory, and boilerplate default files in the root config.

The boilerplate files should be controlled by a colonize "template" that would define what files should be created when initializing a new project.

**Comment by jyore** [comment]
I think that this command will also not need the 'environment' flag similar to what's mentioned in #3
